### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by datawookie** [rayheberer/imgnoise#6]
Hey!

Your package is looking great and the functionality works perfectly.

There is just one thing missing: you were supposed to provide some data to go along with the package. In your case this should be easy, right? You can provide image data in a .rda file. Choose an interesting image! But make sure that it's fairly small since it should not bloat the package too much.

Thanks, Andrew.

**Comment by rayheberer** [comment]
just saw this! I'll make sure to add some data over the weekend.

**Comment by datawookie** [comment]
Great. No rush. Just get to it when you can.

**Comment by rayheberer** [comment]
I've added an [example image](https://en.wikipedia.org/wiki/Hadley_Wickham#/media/File:Hadley-wickham2016-02-04.jpg). It's taken from wikipedia, and is free to use.

**Comment by datawookie** [comment]
Hehe. Well played.
